seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: <your_dir>
      name: trainer_name
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 10
        monitor: val/loss
  max_epochs: 50
  check_val_every_n_epoch: 2
  log_every_n_steps: 10
  enable_checkpointing: True
  default_root_dir: <your_dir>

data:
  class_path: Landslide4SenseNonGeoDataModule
  init_args:
    batch_size: 8
    num_workers: 12
    bands:
      - BLUE
      - GREEN
      - RED
      # - RED_EDGE_1
      # - RED_EDGE_2
      # - RED_EDGE_3
      - NIR_BROAD
      - SWIR_1
      - SWIR_2
    train_transform:
      - class_path: albumentations.Flip
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    test_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    data_root: <dataset_dir> # https://huggingface.co/datasets/ibm-nasa-geospatial/Landslide4sense

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      backbone_pretrained: True
      backbone: <prithvi_model> # prithvi_vit_100, prithvi_eo_v2_300, prithvi_eo_v2_300_tl, prithvi_eo_v2_600, prithvi_eo_v2_600_tl
      decoder: UperNetDecoder
      num_classes: 2
      rescale: True
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        # - RED_EDGE_1
        # - RED_EDGE_2
        # - RED_EDGE_3
        - NIR_BROAD
        - SWIR_1
        - SWIR_2
      head_dropout: 0.1
      decoder_channels: 256
      head_channel_list:
        - 128
        - 64
      necks:
        - name: SelectIndices
          indices:
            # indices for prithvi_vit_100
            # - 2
            # - 5
            # - 8
            # - 11
            # indices for prithvi_eo_v2_300
            # - 5
            # - 11
            # - 17
            # - 23
            # indices for prithvi_eo_v2_600
            - 7
            - 15
            - 23
            - 31
        - name: ReshapeTokensToImage
    loss: focal
    freeze_backbone: false
    freeze_decoder: false
    model_factory: EncoderDecoderFactory

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5.0e-5
    weight_decay: 0.1

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 50